_ASCII_LOWERCASE = 'abcdefghijklmnopqrstuvwxyz'
_ASCII_UPPERCASE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
_CYRILLIC_LOWERCASE = 'абвгдеёжзийклмнопрстуфхцчшщъыьэюяі'
_CYRILLIC_UPPERCASE = 'АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯІ'

_LEN_ASCII_LOWERCASE = len(_ASCII_LOWERCASE)
_LEN_ASCII_UPPERCASE = len(_ASCII_UPPERCASE)
_LEN_CYRILLIC_LOWERCASE = len(_CYRILLIC_LOWERCASE)
_LEN_CYRILLIC_UPPERCASE = len(_CYRILLIC_UPPERCASE)